import { computeBlockers, needsDetectorAnswer, questionsForTurn, type Blocker } from "./blockers.ts";
import { hashCanonical } from "./canonical.ts";
import { ScopeDraftV1Schema, type ScopeDraftV1, type ScopeExtraction } from "./scope.ts";
import type { ReceiptStatus } from "./signals.ts";

/**
 * Deterministic scope receipt (PRD §9.2). Generated by code, never by the LLM.
 * Chat surfaces must show `lines` verbatim and in order.
 */
export interface Receipt {
  receipt_id: string;
  version: number;
  run_id: string;
  status: ReceiptStatus;
  requester_person_id: string;
  route: { platform: string; space_id: string; thread_id: string; session_generation: number };
  extraction: ScopeExtraction;
  blockers: Blocker[];
  /** Present only when status is AWAITING_APPROVAL. */
  scope: ScopeDraftV1 | null;
  scope_hash: string | null;
  approval_action: string | null;
  notes: string[];
  lines: string[];
}

export interface BuildReceiptInput {
  runId: string;
  version: number;
  requesterPersonId: string;
  route: Receipt["route"];
  extraction: ScopeExtraction;
  notes?: string[];
}

export function receiptIdFor(runId: string, version: number): string {
  const short = runId.replace(/[^a-zA-Z0-9]/g, "").slice(0, 10).toUpperCase();
  return `R-${short}-${version}`;
}

export function formatAddress(p: ScopeExtraction["property"]): string | null {
  if (!p.line1 || !p.city || !p.region) return null;
  return `${p.line1}, ${p.city}, ${p.region}${p.postal_code ? ` ${p.postal_code}` : ""}`;
}

/** Convert a blocker-free extraction to the PRD contract. Throws if blockers remain. */
export function toScopeDraft(s: ScopeExtraction): ScopeDraftV1 {
  const blockers = computeBlockers(s);
  if (blockers.length) throw new Error(`Scope still has blockers: ${blockers.map((b) => b.field).join(", ")}`);
  const status = s.existing_equipment.status;
  const draft: ScopeDraftV1 = {
    schema: "preliminary_scope_draft_v1",
    client: s.client!,
    property: formatAddress(s.property)!,
    project_type: s.project_type!,
    market: s.market as ScopeDraftV1["market"],
    room_types: s.room_types,
    functional_systems: s.functional_systems,
    requested_changes: s.requested_changes,
    requested_quantities: s.requested_quantities,
    existing_equipment_disposition: status === "not_provided" ? "unknown" : status,
    retained_equipment: s.existing_equipment.retained,
    existing_detectors: needsDetectorAnswer(s) && s.existing_detectors !== "not_provided" ? s.existing_detectors : "not_applicable",
    excluded_scope: s.excluded_scope,
    service_categories: s.service_categories,
    unresolved_questions: s.unresolved_questions,
    size: s.size,
    budget:
      s.budget.status === "known"
        ? { status: "known", amount: s.budget.amount_usd!, currency: "USD" }
        : { status: "unknown" },
    target_installation_date: s.target_installation_date!,
  };
  // An UNASSIGNED or partial selector does not identify a real source quote (PRD §8.1).
  if (s.proposal.number && s.proposal.number !== "UNASSIGNED" && s.proposal.name) {
    draft.source_quote_selector = { number: s.proposal.number, name: s.proposal.name };
  }
  return ScopeDraftV1Schema.parse(draft);
}

const none = (xs: string[]) => (xs.length ? xs.join("; ") : "none");
const usd = (n: number) => `$${n.toLocaleString("en-US", { maximumFractionDigits: 2 })}`;

function scopeLines(s: ScopeExtraction): string[] {
  const missing = "— (needed)";
  const eq = s.existing_equipment;
  const equipment =
    eq.status === "not_provided"
      ? missing
      : eq.status === "described"
        ? `keep: ${none(eq.retained)} | replace/remove: ${none(eq.removed_or_replaced)}`
        : eq.status;
  const proposal =
    s.proposal.number && s.proposal.number !== "UNASSIGNED"
      ? `${s.proposal.number}${s.proposal.name ? ` "${s.proposal.name}"` : " (no quote name given; not used as a source quote)"}`
      : "UNASSIGNED (draft)";
  return [
    `Client: ${s.client ?? missing}`,
    `Property: ${formatAddress(s.property) ?? missing}`,
    `Proposal: ${proposal}`,
    `Project type: ${s.project_type ?? missing}`,
    `Market: ${s.market === "not_provided" ? missing : s.market}`,
    `Rooms/areas: ${s.room_types.length ? s.room_types.join("; ") : missing}`,
    `Systems: ${s.functional_systems.length ? s.functional_systems.join("; ") : missing}`,
    `Requested outcomes: ${s.requested_changes.length ? s.requested_changes.join("; ") : missing}`,
    ...(s.requested_quantities.length ? [`Stated quantities: ${s.requested_quantities.map((q) => `${q.item} × ${q.quantity}`).join("; ")}`] : []),
    `Existing equipment: ${equipment}`,
    ...(needsDetectorAnswer(s)
      ? [`Existing smoke/CO detectors: ${{ not_provided: missing, none: "none", keep_and_monitor: "keep and monitor", replace: "replace with new" }[s.existing_detectors]}`]
      : []),
    `Excluded: ${none(s.excluded_scope)}`,
    `Services: ${s.service_categories.length ? s.service_categories.join("; ") : missing}`,
    `Size: ${s.size ? `${s.size.value.toLocaleString("en-US")} ${s.size.unit}` : "unknown"}`,
    `Budget: ${s.budget.status === "known" ? usd(s.budget.amount_usd!) : s.budget.status === "unknown" ? "unknown" : missing}`,
    `Target install: ${s.target_installation_date ?? missing}`,
  ];
}

export function buildReceipt(input: BuildReceiptInput): Receipt {
  const receiptId = receiptIdFor(input.runId, input.version);
  const blockers = computeBlockers(input.extraction);
  const status: ReceiptStatus = blockers.length ? "NEEDS_CLARIFICATION" : "AWAITING_APPROVAL";
  const scope = status === "AWAITING_APPROVAL" ? toScopeDraft(input.extraction) : null;
  const scopeHash = scope ? hashCanonical(scope) : null;
  const approvalAction = scope ? `Approve scope ${receiptId}` : null;
  const notes = input.notes ?? [];

  const lines = [`Scope receipt ${receiptId} (version ${input.version})`, `Status: ${status}`, ...scopeLines(input.extraction)];
  if (input.extraction.unresolved_questions.length) {
    lines.push(`Open items (not blocking): ${input.extraction.unresolved_questions.join("; ")}`);
  }
  for (const note of notes) lines.push(`Note: ${note}`);
  if (status === "NEEDS_CLARIFICATION") {
    const asked = questionsForTurn(blockers);
    lines.push("Blocking questions:");
    asked.forEach((b, i) => lines.push(`${i + 1}. ${b.question}`));
    if (blockers.length > asked.length) lines.push(`(${blockers.length - asked.length} more after these)`);
  } else {
    lines.push(`Scope hash: ${scopeHash}`);
    lines.push(`To approve: ${approvalAction}`);
  }

  return {
    receipt_id: receiptId,
    version: input.version,
    run_id: input.runId,
    status,
    requester_person_id: input.requesterPersonId,
    route: input.route,
    extraction: input.extraction,
    blockers,
    scope,
    scope_hash: scopeHash,
    approval_action: approvalAction,
    notes,
    lines,
  };
}

const APPROVAL_RE = /^\s*approve scope\s+(R-[A-Z0-9]+-\d+)\s*$/i;

/** Parse the text approval form `Approve scope <receipt_id>`. */
export function parseApprovalText(text: string): string | null {
  const m = APPROVAL_RE.exec(text);
  return m ? m[1]!.toUpperCase() : null;
}
